export const TRAY_REPORT_VARIABLES = [
  { id: 'tray-details:reported-at', name: 'Report generated at', placeholder: '{{REPORTDATE}}' },
  {
    id: 'tray-details:tray-weight-per-meter',
    name: 'Tray weight excluding supports [kg/m]',
    placeholder: '{{TRAYOWNPERMETER}}',
  },
  {
    id: 'tray-details:span-mass',
    name: 'Cables plus tray mass [kg/m]',
    placeholder: '{{SPANMASS}}',
  },
  {
    id: 'tray-details:span-load-formula',
    name: 'Unfactored tray span load calculation [kN/m]',
    placeholder: '{{SPANLOADFORMULA}}',
  },
  {
    id: 'tray-details:design-load-formula',
    name: 'Design load calculation with safety allowance [kN/m]',
    placeholder: '{{DESIGNLOADFORMULA}}',
  },
  {
    id: 'tray-details:allowable-load-formula',
    name: 'Allowable load interpolation calculation [kN/m]',
    placeholder: '{{ALLOWABLELOADFORMULA}}',
  },
  {
    id: 'tray-details:load-utilization',
    name: 'Load capacity utilization [%]',
    placeholder: '{{LOADUTILIZATION}}',
  },
  {
    id: 'tray-details:load-utilization-formula',
    name: 'Load utilization calculation [%]',
    placeholder: '{{LOADUTILIZATIONFORMULA}}',
  },
  {
    id: 'tray-details:load-reserve',
    name: 'Remaining design load capacity [kN/m]',
    placeholder: '{{LOADRESERVE}}',
  },
  {
    id: 'tray-details:load-reserve-formula',
    name: 'Remaining design load capacity calculation [kN/m]',
    placeholder: '{{LOADRESERVEFORMULA}}',
  },
  {
    id: 'tray-details:load-reserve-percent',
    name: 'Remaining design load capacity [%]',
    placeholder: '{{LOADRESERVEPERCENT}}',
  },
  {
    id: 'tray-details:max-allowable-span',
    name: 'Maximum allowable span within curve range [m]',
    placeholder: '{{MAXALLOWABLESPAN}}',
  },
  {
    id: 'tray-details:load-verification',
    name: 'Load verification conclusion',
    placeholder: '{{LOADVERIFICATION}}',
  },
  {
    id: 'tray-details:load-range',
    name: 'Documented load curve span range [m]',
    placeholder: '{{LOADRANGE}}',
  },
  {
    id: 'tray-details:free-space-percent',
    name: 'Free width result [%]',
    placeholder: '{{FREEWIDTHRESULT}}',
  },
  {
    id: 'tray-details:free-space-verification',
    name: 'Free width verification against project limits',
    placeholder: '{{FREEWIDTHVERIFICATION}}',
  },
] as const;

// These are Variables API row IDs, shared by the template, editor and exporter.
export const TRAY_REPORT_PLACEHOLDERS: Record<string, string> = {
  'details:project-number': '{{PROJECTNUMBER}}',
  'details:project-name': '{{PROJECTNAME}}',
  'details:customer': '{{CUSTOMER}}',
  'details:current-user': '{{PREPAREDBY}}',
  'details:cable-spacing': '{{CABLESPACING}}',
  'details:bundle-spacing-free': '{{BUNDLESPACINGFREE}}',
  'details:min-free-space': '{{MINFREEWIDTH}}',
  'details:max-free-space': '{{MAXFREEWIDTH}}',
  'tray-details:name': '{{TRAYNAME}}',
  'tray-details:type': '{{TRAYTYPE}}',
  'tray-details:manufacturer': '{{TRAYMANUFACTURER}}',
  'tray-details:purpose': '{{TRAYPURPOSE}}',
  'tray-details:width': '{{TRAYWIDTH}}',
  'tray-details:height': '{{TRAYHEIGHT}}',
  'tray-details:length': '{{TRAYLENGTH}}',
  'tray-details:occupied-space': '{{DIAMETERSSUM}}',
  'tray-details:free-space': '{{FREESPACE}}',
  'tray-details:grounding-note': '{{GROUNDINGNOTE}}',
  'tray-details:rung-height': '{{RUNGHEIGHT}}',
  'tray-details:useful-height': '{{USEFULTRAY}}',
  'tray-details:tray-type-image': '{{TRAYPICTURE}}',
  'tray-details:load-curve-name': '{{LOADCURVENAME}}',
  'tray-details:safety-factor': '{{SAFETYFACTOR}}',
  'tray-details:calculated-span': '{{CALCULATEDSPAN}}',
  'tray-details:calculated-load': '{{DESIGNLOAD}}',
  'tray-details:allowable-load': '{{ALLOWABLELOAD}}',
  'tray-details:load-curve-status': '{{LOADSTATUS}}',
  'tray-details:load-curve-canvas': '{{DIAGRAMTRAYPIC}}',
  'tray-details:weight-load-per-meter': '{{TRAYLOADPERMETER}}',
  'tray-details:total-own-weight': '{{TRAYCALCWEIGHT}}',
  'tray-details:cables-weight-load-per-meter': '{{CABLESWEIGHTPERMETER}}',
  'tray-details:cables-total-weight': '{{CABLESWEIGHTCALCULATIONS}}',
  'tray-details:total-weight-load-per-meter': '{{TOTALPERPOINT}}',
  'tray-details:total-weight': '{{TOTALCALC}}',
  'tray-details:cables-table': '{{CABLESTABLE}}',
  'tray-details:support-type': '{{SUPPORTTYPE}}',
  'tray-details:support-length': '{{SUPPORTLENGTH}}',
  'tray-details:support-distance': '{{DISTANCE}}',
  'tray-details:supports-count': '{{SUPPORTSCOUNT}}',
  'tray-details:support-weight-per-piece': '{{SUPPORTWEIGHT}}',
  'tray-details:supports-total-weight': '{{SUPPTOTALWEIGHT}}',
  'tray-details:supports-weight-per-meter': '{{SUPPWEIGHTPERMETER}}',
  'tray-details:concept-canvas': '{{FILLPICTURE}}',
  ...Object.fromEntries(
    TRAY_REPORT_VARIABLES.map((variable) => [variable.id, variable.placeholder]),
  ),
};
